### ISSUE TITLE
thumbnail image cache doesn't work with capistrano deployments

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/ark-manager#81]
Requests for thumbnail images (`ark:/50959/[:id]/thumbnail`) are cached in the application's internal `tmp/cache/previews` directory, which was implemented via https://github.com/boston-library/ark-manager/commit/fd939541e1ac30e14b377bab259948bfaf6355eb.

However, every time we deploy the application via Capistrano, it creates a new copy of the application code in `railsApps/ark-manager/releases`.

This means that the cache does not persist between releases.

However, something in the stack (either the app, puma, or web server) thinks it does. This can cause thumbnail URLs to return a 404, since stack is looking for a file that doesn't exist.

Here is an example of a 404 returned by a request for `https://ark-dc3dev.bpl.org/ark:/50959/rn301202h/thumbnail`:
```
I, [2023-08-03T12:08:08.571383 #45951]  INFO -- : [1d94d910-e871-46ef-8878-07d4c1a5bdc2] Started GET "/ark:/50959/rn301202h/thumbnail" for 10.20.72.64 at 2023-08-03 12:08:08 -0400
I, [2023-08-03T12:08:08.572487 #45951]  INFO -- : [1d94d910-e871-46ef-8878-07d4c1a5bdc2] Processing by PreviewController#thumbnail as HTML
I, [2023-08-03T12:08:08.572588 #45951]  INFO -- : [1d94d910-e871-46ef-8878-07d4c1a5bdc2]   Parameters: {"ark"=>"ark:", "namespace"=>"50959", "noid"=>"rn301202h"}
I, [2023-08-03T12:08:08.578445 #45951]  INFO -- request: [1d94d910-e871-46ef-8878-07d4c1a5bdc2] GET https://index-dc3dev.bpl.org/solr/curator_staging/get?id=bpl-dev%3Arn301202h&wt=json
I, [2023-08-03T12:08:08.578526 #45951]  INFO -- request: [1d94d910-e871-46ef-8878-07d4c1a5bdc2] User-Agent: "BPL-Ark-Manager/2"
I, [2023-08-03T12:08:08.593424 #45951]  INFO -- response: [1d94d910-e871-46ef-8878-07d4c1a5bdc2] Status 200
I, [2023-08-03T12:08:08.593545 #45951]  INFO -- response: [1d94d910-e871-46ef-8878-07d4c1a5bdc2] server: "nginx"
date: "Thu, 03 Aug 2023 16:08:08 GMT"
content-type: "application/json;charset=utf-8"
content-length: "3197"
connection: "keep-alive"
content-security-policy: "default-src 'none'; base-uri 'none'; connect-src 'self'; form-action 'self'; font-src 'self'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; worker-src 'self';"
x-content-type-options: "nosniff"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
last-modified: "Tue, 01 Aug 2023 18:10:22 GMT"
etag: "\"ZjY5ZWFlMDAwMDAwMDAwMFNvbHI=--gzip\""
vary: "Accept-Encoding, User-Agent"
strict-transport-security: "max-age=31536000; includeSubDomains"
I, [2023-08-03T12:08:08.712253 #45951]  INFO -- : [1d94d910-e871-46ef-8878-07d4c1a5bdc2] Sent file /home/deployer/railsApps/ark-manager/releases/20230731180144/tmp/cache/previews/bpl-dev:ns064667c_thumbnail.jpg (0.4ms)
I, [2023-08-03T12:08:08.712531 #45951]  INFO -- : [1d94d910-e871-46ef-8878-07d4c1a5bdc2] Completed 200 OK in 140ms (ActiveRecord: 2.9ms | Allocations: 3511)
I, [2023-08-03T12:08:08.713954 #45951]  INFO -- : [2106ff99-33f7-47af-a500-ff1c6475d974] Started GET "/home/deployer/railsApps/ark-manager/releases/20230731180144/tmp/cache/previews/bpl-dev:ns064667c_thumbnail.jpg" for 10.20.72.64 at 2023-08-03 12:08:08 -0400
I, [2023-08-03T12:08:08.714877 #45951]  INFO -- : [2106ff99-33f7-47af-a500-ff1c6475d974] Processing by ApplicationController#route_not_found as JPEG
I, [2023-08-03T12:08:08.714933 #45951]  INFO -- : [2106ff99-33f7-47af-a500-ff1c6475d974]   Parameters: {"path"=>"home/deployer/railsApps/ark-manager/releases/20230731180144/tmp/cache/previews/bpl-dev:ns064667c_thumbnail"}
E, [2023-08-03T12:08:08.715063 #45951] ERROR -- : [2106ff99-33f7-47af-a500-ff1c6475d974] =============================================
E, [2023-08-03T12:08:08.715089 #45951] ERROR -- : [2106ff99-33f7-47af-a500-ff1c6475d974] ActionController::RoutingError
E, [2023-08-03T12:08:08.715109 #45951] ERROR -- : [2106ff99-33f7-47af-a500-ff1c6475d974] No Route Matches This Url
E, [2023-08-03T12:08:08.715288 #45951] ERROR -- : [2106ff99-33f7-47af-a500-ff1c6475d974] ["/home/deployer/railsApps/ark-manager/releases/20230731180144/app/controllers/application_controller.rb:33:in `route_not_found'", "/home/deployer/railsApps/ark-manager/shared/bundle/ruby/3.0.0/gems/actionpack-6.1.7.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/home/deployer/railsApps/ark-manager/shared/bundle/ruby/3.0.0/gems/actionpack-6.1.7.4/lib/abstract_controller/base.rb:228:in `process_action'", "/home/deployer/railsApps/ark-manager/shared/bundle/ruby/3.0.0/gems/actionpack-6.1.7.4/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/home/deployer/railsApps/ark-manager/shared/bundle/ruby/3.0.0/gems/actionpack-6.1.7.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'"]
E, [2023-08-03T12:08:08.715366 #45951] ERROR -- : [2106ff99-33f7-47af-a500-ff1c6475d974] =============================================
I, [2023-08-03T12:08:08.715546 #45951]  INFO -- : [2106ff99-33f7-47af-a500-ff1c6475d974] Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 193)

```

The request is for a file that doesn't exist yet:
```
/home/deployer/railsApps/ark-manager/releases/20230731180144/tmp/cache/previews/bpl-dev:ns064667c_thumbnail.jpg
```
That file is actually at:
```
/home/deployer/railsApps/ark-manager/releases/20230726140149/tmp/cache/previews/bpl-dev:ns064667c_thumbnail.jpg
```

**Possible solutions:**
* Clear the cache every time there is a new release
  This isn't a great option, because all the previous efforts to cache files and speed up response time will be lost. This will be especially problematic in production.

* Symlink the `tmp/cache` directory to another location on the filesystem that is persisted and can be shared by each release

*  ??? - maybe Capistrano has some way of dealing with this problem?

**Comment by ebenenglish** [comment]
For comparison, here is a successful thumbnail request in production:
```
I, [2023-08-03T16:53:14.979589 #18560]  INFO -- : [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] Started GET "/ark:/50959/ht24zj99q/thumbnail" for 66.249.66.36 at 2023-08-03 16:53:14 -0400
I, [2023-08-03T16:53:14.980470 #18560]  INFO -- : [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] Processing by PreviewController#thumbnail as HTML
I, [2023-08-03T16:53:14.980525 #18560]  INFO -- : [0274d9b6-bcca-4270-a2de-a6ee854b1f9c]   Parameters: {"ark"=>"ark:", "namespace"=>"50959", "noid"=>"ht24zj99q"}
I, [2023-08-03T16:53:14.984085 #18560]  INFO -- request: [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] GET https://index.digitalcommonwealth.org/solr/curator_production/get?id=commonwealth%3Aht24zj99q&wt=json
I, [2023-08-03T16:53:14.984135 #18560]  INFO -- request: [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] User-Agent: "BPL-Ark-Manager/2"
I, [2023-08-03T16:53:14.986087 #18560]  INFO -- response: [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] Status 200
I, [2023-08-03T16:53:14.986150 #18560]  INFO -- response: [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] server: "nginx"
date: "Thu, 03 Aug 2023 20:53:14 GMT"
content-type: "application/json;charset=utf-8"
content-length: "3542"
connection: "keep-alive"
content-security-policy: "default-src 'none'; base-uri 'none'; connect-src 'self'; form-action 'self'; font-src 'self'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; worker-src 'self';"
x-content-type-options: "nosniff"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
last-modified: "Thu, 03 Aug 2023 19:03:45 GMT"
etag: "\"NzMxN2JiMDAwMDAwMDAwMFNvbHI=--gzip\""
vary: "Accept-Encoding, User-Agent"
strict-transport-security: "max-age=31536000; includeSubDomains"
I, [2023-08-03T16:53:15.063970 #18560]  INFO -- : [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] Sent file /home/dc3admin/railsApps/ark-manager/tmp/cache/previews/commonwealth:ht24zk008_thumbnail.jpg (0.2ms)
I, [2023-08-03T16:53:15.064121 #18560]  INFO -- : [0274d9b6-bcca-4270-a2de-a6ee854b1f9c] Completed 200 OK in 84ms (ActiveRecord: 1.6ms | Allocations: 3156)
```
